# MySQL database credentials secret
---
apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cm9vdA==
  SPRING_DATASOURCE_PASSWORD: cm9vdA==
---
# SonarQube database credentials secret
apiVersion: v1
kind: Secret
metadata:
  name: sonar-db-secret
type: Opaque
stringData:
  username: "sonar"
  password: "sonar"